--[[
    GLOBAL VARIABLES
    JELLY ENGINE RPG
    Maxime Blanc
    https://github.com/salty-max
]]

TITLE = 'JELLY ENGINE'

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 640
VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 384

PLAYER_WALK_SPEED = 200
PLAYER_FRICTION = 0.02
