--[[
    GLOBAL VARIABLES
    JELLY ENGINE RPG
    Maxime Blanc
    https://github.com/salty-max
]]

TITLE = 'JELLY ENGINE'

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 640
VIRTUAL_WIDTH = 128
VIRTUAL_HEIGHT = 128

PLAYER_WALK_SPEED = 40
